//! `bullarchy editor-setup` — writes LSP configuration for detected editors.
//!
//! Resolves the absolute path of the `bullang` binary for LSP configs.
//! The LSP server is provided by `bullang lsp` — make sure bullang is installed.

pub fn cmd_editor_setup() {
    use std::io::Write;
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    let mut configured = 0usize;
    let mut skipped    = 0usize;

    // Resolve the absolute path of the `bullang` binary for LSP configuration.
    // The LSP server lives in bullang, not bullarchy. Falls back to "bullang"
    // (relies on PATH) if `which` resolution fails.
    let bin = which_bullang().unwrap_or_else(|| "bullang".to_string());

    println!("bullarchy editor-setup");
    println!("  binary : {}", bin);
    println!();

    // ── Neovim ───────────────────────────────────────────────────────────────
    let nvim_dir = std::path::PathBuf::from(&home).join(".config").join("nvim");
    if nvim_dir.exists() {
        let ftdetect = nvim_dir.join("after").join("ftdetect");
        std::fs::create_dir_all(&ftdetect).ok();
        let ftfile = ftdetect.join("bullang.vim");
        if !ftfile.exists() {
            let _ = std::fs::write(&ftfile,
                "au BufRead,BufNewFile *.bu set filetype=bullang\n");
            println!("  [Neovim] wrote {}", ftfile.display());
            configured += 1;
        } else {
            println!("  [Neovim] {} exists \u{2014} skipped", ftfile.display());
            skipped += 1;
        }

        let plugin_dir = nvim_dir.join("after").join("plugin");
        std::fs::create_dir_all(&plugin_dir).ok();
        let lua_file = plugin_dir.join("bullang.lua");
        if !lua_file.exists() {
            let lua = format!(
                "-- Bullang LSP (auto-generated by `bullarchy editor-setup`)\n\
                local ok, lspconfig = pcall(require, \"lspconfig\")\n\
                if not ok then return end\n\
                local configs = require(\"lspconfig.configs\")\n\
                if not configs.bullang then\n\
                  configs.bullang = {{\n\
                    default_config = {{\n\
                      cmd = {{ \"{bin}\", \"lsp\" }},\n\
                      filetypes = {{ \"bullang\" }},\n\
                      root_dir = lspconfig.util.root_pattern(\"inventory.bu\"),\n\
                    }},\n\
                  }}\n\
                end\n\
                lspconfig.bullang.setup({{}})\n",
                bin = bin
            );
            let _ = std::fs::write(&lua_file, &lua);
            println!("  [Neovim] wrote {}", lua_file.display());
            println!("           (requires nvim-lspconfig)");
            configured += 1;
        } else {
            println!("  [Neovim] {} exists \u{2014} skipped", lua_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Neovim] not detected (~/.config/nvim not found)");
    }
    println!();


    // ── Vim (ALE) ────────────────────────────────────────────────────────────
    let vim_dir = std::path::PathBuf::from(&home).join(".vim");
    if vim_dir.exists() {
        let ftdetect = vim_dir.join("ftdetect");
        std::fs::create_dir_all(&ftdetect).ok();
        let ftfile = ftdetect.join("bullang.vim");
        if !ftfile.exists() {
            let _ = std::fs::write(&ftfile,
                "au BufRead,BufNewFile *.bu set filetype=bullang\n");
            println!("  [Vim] wrote {}", ftfile.display());
            configured += 1;
        } else {
            println!("  [Vim] {} exists \u{2014} skipped", ftfile.display());
            skipped += 1;
        }
        let plugin_dir = vim_dir.join("after").join("plugin");
        std::fs::create_dir_all(&plugin_dir).ok();
        let vim_file = plugin_dir.join("bullang.vim");
        if !vim_file.exists() {
            let content = format!(
                r#"" Bullang LSP via ALE (auto-generated by bullarchy editor-setup)
" Requires ALE: https://github.com/dense-analysis/ale
call ale#linter#Define('bullang', {{
\  'name':         'bullang_lsp',
\  'lsp':          'stdio',
\  'executable':   '{bin}',
\  'command':      '{bin} lsp',
\  'project_root': function('ale#util#FindNearestFile', ['inventory.bu']),
\}})
let g:ale_linters = get(g:, 'ale_linters', {{}})
let g:ale_linters['bullang'] = ['bullang_lsp']
"#,
                bin = bin
            );
            let _ = std::fs::write(&vim_file, &content);
            println!("  [Vim] wrote {}", vim_file.display());
            println!("        (requires ALE: https://github.com/dense-analysis/ale)");
            configured += 1;
        } else {
            println!("  [Vim] {} exists \u{2014} skipped", vim_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Vim] not detected (~/.vim not found)");
    }
    println!();

    // ── Helix ────────────────────────────────────────────────────────────────
    let helix_dir = std::path::PathBuf::from(&home).join(".config").join("helix");
    if helix_dir.exists() {
        let lang_file = helix_dir.join("languages.toml");
        let existing  = std::fs::read_to_string(&lang_file).unwrap_or_default();
        if existing.contains(r#"name = "bullang""#) {
            println!("  [Helix] bullang already in languages.toml \u{2014} skipped");
            skipped += 1;
        } else {
            let entry = format!(
                "\n[[language]]\n\
                name = \"bullang\"\n\
                scope = \"source.bullang\"\n\
                file-types = [\"bu\"]\n\
                comment-token = \"//\"\n\
                language-servers = [\"bullang-lsp\"]\n\
                \n\
                [language-server.bullang-lsp]\n\
                command = \"{bin}\"\n\
                args = [\"lsp\"]\n",
                bin = bin
            );
            let mut f = std::fs::OpenOptions::new()
                .create(true).append(true).open(&lang_file)
                .expect("cannot open languages.toml");
            let _ = f.write_all(entry.as_bytes());
            println!("  [Helix] appended to {}", lang_file.display());
            configured += 1;
        }
    } else {
        println!("  [Helix] not detected (~/.config/helix not found)");
    }
    println!();

    // ── Emacs (eglot) ────────────────────────────────────────────────────────
    let emacs_dir = std::path::PathBuf::from(&home).join(".emacs.d");
    if emacs_dir.exists() {
        let el_file = emacs_dir.join("bullang-lsp.el");
        if !el_file.exists() {
            let el = format!(
                ";; Bullang LSP (auto-generated by `bullarchy editor-setup`)\n\
                ;; Add to init.el: (load (expand-file-name \"bullang-lsp.el\" user-emacs-directory))\n\
                (require 'eglot)\n\
                (add-to-list 'auto-mode-alist '(\"\\\\.bu\\\\'\" . prog-mode))\n\
                (add-to-list 'eglot-server-programs\n\
                             '(prog-mode . (\"{bin}\" \"lsp\")))\n\
                (add-hook 'prog-mode-hook\n\
                          (lambda ()\n\
                            (when (and buffer-file-name\n\
                                       (string-suffix-p \".bu\" buffer-file-name))\n\
                              (eglot-ensure))))\n",
                bin = bin
            );
            let _ = std::fs::write(&el_file, &el);
            println!("  [Emacs] wrote {}", el_file.display());
            println!(r#"          add to init.el: (load (expand-file-name "bullang-lsp.el" user-emacs-directory))"#);
            configured += 1;
        } else {
            println!("  [Emacs] {} exists \u{2014} skipped", el_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Emacs] not detected (~/.emacs.d not found)");
    }
    println!();

    // ── VS Code ───────────────────────────────────────────────────────────────
    println!("  [VS Code] install the extension (.vsix) from:");
    println!("            https://github.com/My-sidequests/Bullang/releases");
    println!("            The extension will use the bullang binary at: {}", bin);
    println!();
    println!("configured: {}   skipped (already set up): {}", configured, skipped);
    if configured > 0 {
        println!();
        println!("binary path embedded: {}", bin);
        println!("if you move or reinstall bullang, re-run `bullarchy editor-setup`");
        println!("(delete the generated files first so they are regenerated)");
    }
}

// ── Helper: locate the bullang binary ────────────────────────────────────────

/// Resolve the absolute path of the `bullang` binary via PATH.
/// Returns None if bullang is not found — callers fall back to "bullang".
fn which_bullang() -> Option<String> {
    let output = std::process::Command::new("which")
        .arg("bullang")
        .output()
        .ok()?;
    if output.status.success() {
        let path = String::from_utf8(output.stdout).ok()?;
        Some(path.trim().to_string())
    } else {
        None
    }
}
