//! Blueprint-based project init: parsing a `.bu` blueprint file and emitting
//! the corresponding folder tree.

use std::path::{Path, PathBuf};
use std::fs;
use super::{rank_for_depth, write_file};

// ── README written into every blueprint project ───────────────────────────────

pub const BULLANG_README: &str = r#"# Bullang — Quick-start README

> This file was generated by `bullang init` and is **automatically deleted** when
> you run `bullang convert`. Keep it as a reference while you write your project,
> then let the converter clean it up.

---

## Folder hierarchy

| Rank       | Depth | Role                              |
|------------|-------|-----------------------------------|
| `skirmish` | 1     | Leaf module — holds source files  |
| `tactic`   | 2     | Groups several skirmishes         |
| `strategy` | 3     | Groups several tactics            |
| `battle`   | 4     | Groups several strategies         |
| `theater`  | 5     | Groups several battles            |
| `war`      | 6     | Top-level root of a large project |

Every folder must contain an `inventory.bu`. Each rank may contain at most
5 sub-folders, 5 source files, 5 functions per file, and 5 bullets per function.

**Flow-downward rule:** functions and structs defined in a child folder are
available to its parent. You cannot call upward or sideways.

---

## The inventory file

Every folder has an `inventory.bu` that describes it entirely:

```
#rank: skirmish;
#lang: rs;
#lib: stdio.h;

struct Vec2 {
    x : f32,
    y : f32,
}

math : add_vec, dot_product;
```

### Directives, to put on top of the inventory.bu file

| Directive | Meaning                                     |
|-----------|---------------------------------------------|
| `#rank:`  | Rank of this folder (required)              |
| `#lang:`  | Target language: `rs` `py` `c` `cpp` `go`   |
| `#lib:`   | C/C++ header to include (repeatable)        |

`#lang:` set on a parent folder propagates to all descendants. A child
declaring a different `#lang:` than its parent is a validation error.

### Struct definitions and source files

Structs are declared in `inventory.bu`.

The rank rule applies to structs too: a struct from a child inventory can be
used in that child's source files and in the parent's inventory and source
files. Never from a sibling or ancestor.

After directives and structs, list every source file and its functions.

---

## Source files

Functions in source files are writen as followed :

```
let add(a: i32, b: i32) -> result: i32 {
    (a, b) : a + b -> {result};
}

let scale_and_add(x: i32, y: i32, factor: i32) -> result: i32 {
    (x, factor) : x * factor -> {scaled};
    (scaled, y) : scaled + y -> {result};
}
```

Bullet syntax: `(inputs) : expression -> {binding};`

The arguments list, nammed the shell, may be empty when the expression uses only literals or
interpolation:

```
let greet(name: String) -> result: String {
    () : "Hello {name}!" -> {result};
}
```

Rules:
- Every binding must be consumed by a later bullet, except the final output.
- The last bullet must bind to the declared output name.
- No binding may be assigned twice.
- Maximum 5 bullets per function, 5 functions per file.

---

## Types

| Bullang type    | Rust           | Python          | Go              | C               | C++                       |
|-----------------|----------------|-----------------|-----------------|-----------------|---------------------------|
| `i32`, `i64`    | `i32`/`i64`    | `int`           | `int32`/`int64` | `int32_t`       | `int32_t`                 |
| `f64`           | `f64`          | `float`         | `float64`       | `double`        | `double`                  |
| `String`        | `String`       | `str`           | `string`        | `char *`        | `std::string`             |
| `bool`          | `bool`         | `bool`          | `bool`          | `bool`          | `bool`                    |
| `Vec[T]`        | `Vec<T>`       | `list`          | `[]T`           | `vec_t` (1)     | `std::vector<T>`          |
| `HashMap[K, V]` | `HashMap<K,V>` | `dict`          | `map[K]V`       | `map_t` (1)     | `std::unordered_map<K,V>` |
| `Option[T]`     | `Option<T>`    | `Optional[T]`   | `*T`            | `T*`            | `std::optional<T>`        |
| `Tuple[T, U]`   | `(T, U)`       | `tuple`         | `Tuple_T_U` (2) | `Tuple_T_U` (3) | `std::tuple<T, U>`        |
| `UserStruct`    | `pub struct`   | `@dataclass`    | `struct`        | `typedef struct`| `struct`                  |

(1) C projects using `Vec[T]` or `HashMap[K,V]` get a `foreign_types.h`
emitted automatically. `map_t` uses string keys only.

(2) Go has no built-in tuple type. Bullang emits a named struct per unique
tuple combination into `types.go` — e.g. `Tuple[i32, f64]` becomes
`Tuple_i32_f64` with fields `V0 int32` and `V1 float64`.

(3) C has no built-in tuple type. Bullang emits a `typedef struct` per unique
tuple combination into the module header — e.g. `Tuple[i32, f64]` becomes
`typedef struct { int32_t v0; double v1; } Tuple_i32_f64;`. In single-file
mode the typedef is written inline at the top of the `.c` file.

---

## Expressions and operators

```
// Arithmetic
(a, b) : a + b -> {result};
(x, y) : x * y -> {product};

// Comparison (returns bool)
(a, b) : a == b -> {equal};
(x)    : x > 0.0 -> {positive};

// Integer and float literals
() : 42 -> {n};
() : 3.14 -> {pi};

// String interpolation
() : "value is {x}" -> {msg};

// Function call
(items) : sum(items) -> {total};
```

Supported operators: `+` `-` `*` `/` `%` `==` `!=` `<` `>` `<=` `>=`

---

## Error propagation (?)

Add `?` after a bullet's binding to propagate `None` or `Err` early. Only
valid when the function's output type is `Option[T]`.
Cannot appear on the last bullet.

```
let safe_root(x: f64) -> result: Option[f64] {
    (x) : x >= 0.0 -> {valid}?;
    @rust
    Some(x.sqrt())
    @end
}
```

The binding after `?` holds the unwrapped inner type (`T` from `Option[T]`).
Each backend emits the appropriate early-exit check (`expr?` in Rust,
`if x is None: return None` in Python, `if x == nil { return nil }` in Go,
`if (!x) { return NULL; }` in C, `if (!x) { return std::nullopt; }` in C++).

---

## Native escape blocks

When pipe syntax cannot express what you need, drop into the target language:

```
let sum_slice(values: Vec[i32]) -> result: i32 {
    @rust
    values.iter().sum()
    @end
}
```

Supported: `@rust`  `@python`  `@c`  `@cpp`  `@go`

**Restriction:** every native block must match the folder's `#lang:`. A
`@python` block in a `#lang: rs` folder is a validation error. `@c` is
accepted in `#lang: cpp` folders.

---

## Standard library (builtin::)

```
let absolute(x: i32) -> result: i32 {
    builtin::abs
}
```

| Category   | Builtins                                                                                       |
|------------|------------------------------------------------------------------------------------------------|
| Math       | `abs` `pow` `powf` `sqrt` `clamp` `min` `max` `log` `exp`                                     |
| Conditions | `tern`                                                                                         |
| String     | `to_upper` `to_lower` `trim` `starts_with` `ends_with` `replace_str` `to_string` `parse_i64` `len` |
| Algorithms | `swap` `insertion_sort` `quick_sort` `merge_sort` `radix_sort`                                 |
| I/O        | `in` `out` `open` `close` `time`                                                               |
| System     | `args` `exit` `env` `sleep`                                                                    |

Run `bullang stdlib --list` for full signatures and descriptions.

---

## Multi-language projects

A project can target different languages in different folders. Declare the
language per folder in the blueprint using a language prefix:

```
war my_project {
    theater engine {
        battle core {}
    }
    python: theater pipeline {
        battle data {}
    }
}
```

The language propagates to all descendants. Converting without `-e` converts
each language boundary independently to `_foldername` next to the source:

```sh
bullang convert my_project       # engine -> rs, pipeline -> py
bullang convert my_project -e rs # ERROR: project uses multiple languages
```

The blueprint stays in the root after conversion and acts as the project's
language topology manifest.

---

## The formatter

```sh
bullang fmt              # rewrite all .bu files to canonical style
bullang fmt --dry-run    # show what would change, write nothing
bullang check            # validate + type-check + report formatting drift
```

Canonical rules: 4-space pipe indentation, colon-aligned struct fields,
directives in order (#rank → #lang → #lib), one blank line between
functions. Escape block contents are never reformatted.

---


## Blueprint example

A blueprint lets you scaffold an entire project structure from a single `.bu` file.
Depth-3 example with all features — owner, goal, and language prefix:

```
// game_engine blueprint

war game_engine {

    theater core {

        battle math {
            strategy linear_algebra {
                tactic vectors {
                    skirmish ops {
                        vec3.bu : cross, dot, normalize, length {
                            goal  : "Core 3D vector arithmetic used everywhere in the engine"
                            owner : "alice"
                        }
                        vec4.bu : scale, lerp;
                    }
                }
            }
        }

        battle memory {
            strategy allocators {
                tactic pool {
                    skirmish slab {
                        slab_alloc.bu : alloc, free, reset {
                            goal  : "Fixed-size slab allocator for hot-path objects"
                            owner : "bob"
                        }
                    }
                }
            }
        }

    }

    python: theater tools {

        battle asset_pipeline {
            strategy import {
                tactic mesh {
                    skirmish gltf {
                        gltf_loader.bu : load_scene, load_mesh {
                            goal  : "Imports glTF 2.0 scenes into the engine asset format"
                            owner : "alice"
                        }
                        gltf_validate.bu : check_indices, check_uvs;
                    }
                }
            }
        }

    }

}
```

Run with:

```sh
bullang init game_engine --blueprint game_engine.bu
```

What gets generated:
- Full folder tree with `inventory.bu` at every level (ranks inferred from depth)
- A stub `.bu` file for every declared file — goal written as a comment at the top if specified
- `blueprint.bu` copied to the root as a topology reference
- `work_division.md` at the root (only when at least one owner is declared), listing each owner's files

Rank keywords (`war`, `theater`, `battle`, …) are optional in the blueprint — you can write them for readability or omit them entirely.

---

## CLI reference

| Command                                     | What it does                                             |
|---------------------------------------------|----------------------------------------------------------|
| `bullang init <name>`                       | Scaffold a new project (depth 2 by default)              |
| `bullang init <name> --depth N`             | Scaffold with a custom hierarchy depth (1–6)             |
| `bullang init <name> --lang <ext>`          | Set the target language at init time                     |
| `bullang init <name> --blueprint <file>`    | Init from a blueprint file                               |
| `bullang convert <folder>`                  | Transpile (reads #lang from inventory, default: rs)      |
| `bullang convert <folder> -e rs`            | Override target language                                 |
| `bullang convert file.bu`                   | Transpile a single file — output written next to source  |
| `bullang convert file.bu -o out.rs`         | Transpile a single file to an explicit path              |
| `bullang fmt`                               | Format all .bu files to canonical style                  |
| `bullang fmt --dry-run`                     | Show what would change without writing                   |
| `bullang check`                             | Validate, type-check, and verify formatting              |
| `bullang stdlib --list`                     | List all builtin functions with signatures               |
| `bullang update`                            | Pull and reinstall from main branch                      |

| `bullang lsp`                               | Start the LSP server                                     |
| `bullang editor-setup`                      | Write LSP config for Neovim / Helix / Emacs              |

---

## Typical workflow

```sh
# 1. Create a project
bullang init my_project --depth 3 --lang rs

# 2. Define structs in inventory.bu files (child structs before parent structs)

# 3. Write function bodies in .bu source files

# 4. Validate and check formatting
bullang check

# 5. Format if needed
bullang fmt

# 6. Convert — this README is deleted automatically
bullang convert my_project

# 7. Compile or run
cd _my_project && cargo build
```

---

*Source: https://github.com/My-sidequests/Bullang*

"#;
// ── Blueprint node ────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum BlueprintNode {
    /// A sub-folder. `lang` is `Some("py")` etc. when written as `python: folder_name {`
    Folder { name: String, lang: Option<String>, children: Vec<BlueprintNode> },
    /// A source file entry. `file` is the stem (no `.bu`).
    /// `goal` is written as a comment at the top of the generated stub file.
    /// `owner` is collected into `work_division.md` if present.
    Entry  {
        file:      String,
        functions: Vec<String>,
        goal:      Option<String>,
        owner:     Option<String>,
    },
}

// ── Parser ────────────────────────────────────────────────────────────────────

/// Parse a blueprint.bu file into a list of top-level nodes.
pub fn parse_blueprint(source: &str) -> Result<Vec<BlueprintNode>, String> {
    let lines: Vec<&str> = source.lines().collect();
    let indent_unit = detect_indent_unit(&lines);
    parse_block(&lines, 0, 0, indent_unit).map(|(nodes, _)| nodes)
}

fn detect_indent_unit(lines: &[&str]) -> usize {
    for line in lines {
        if line.trim().is_empty() || line.trim_start().starts_with("//") { continue; }
        let spaces = line.len() - line.trim_start().len();
        if spaces > 0 { return spaces; }
    }
    4 // default
}

/// Recursively parse a block of lines at `base_indent` depth.
/// Returns (nodes, index of next unprocessed line).
fn parse_block(
    lines:       &[&str],
    start:       usize,
    base_indent: usize,
    unit:        usize,
) -> Result<(Vec<BlueprintNode>, usize), String> {
    let mut nodes = Vec::new();
    let mut i     = start;

    while i < lines.len() {
        let line    = lines[i];
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("//") { i += 1; continue; }

        let indent = line.len() - line.trim_start().len();

        if indent < base_indent { break; }

        // Bare closing brace — folder closer written by the user; skip gracefully.
        // Folder nesting is tracked by indentation, not braces, so this is decorative.
        if trimmed == "}" { i += 1; continue; }

        if indent > base_indent {
            return Err(format!(
                "line {}: unexpected indentation (expected {} spaces, got {}): '{}'",
                i + 1, base_indent, indent, trimmed
            ));
        }

        // Entry lines contain `.bu` immediately followed by whitespace + `:`.
        // This distinguishes them from folder lines even when both end with `{`.
        if is_entry_line(trimmed) {
            let entry_line_no = i + 1; // 1-based, for error messages
            let (file_stem, fns_str, has_meta) = parse_entry_header(trimmed, entry_line_no)?;

            let functions: Vec<String> = fns_str
                .split(',')
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty())
                .collect();

            i += 1;

            let (goal, owner, next) = if has_meta {
                parse_metadata_block(lines, i, base_indent, unit, entry_line_no)?
            } else {
                (None, None, i)
            };

            nodes.push(BlueprintNode::Entry { file: file_stem, functions, goal, owner });
            i = next;

        } else if trimmed.ends_with('{') || trimmed.ends_with(':') {
            // Folder line: `folder_name {` or `lang: folder_name {`
            let (lang, folder_name) = parse_folder_header(trimmed);
            if folder_name.is_empty() {
                return Err(format!("line {}: empty folder name", i + 1));
            }
            i += 1;
            let (children, next) = parse_block(lines, i, base_indent + unit, unit)?;
            nodes.push(BlueprintNode::Folder { name: folder_name, lang, children });
            i = next;

        } else {
            return Err(format!(
                "line {}: expected a folder ('name {{') or a file entry ('name.bu : fn1, fn2') — got '{}'",
                i + 1, trimmed
            ));
        }
    }

    Ok((nodes, i))
}

/// True when `trimmed` is a file-entry line: contains `.bu` immediately
/// followed (after optional whitespace) by `:`.
fn is_entry_line(trimmed: &str) -> bool {
    if let Some(pos) = trimmed.find(".bu") {
        trimmed[pos + 3..].trim_start().starts_with(':')
    } else {
        false
    }
}

/// Parse the header of an entry line: `filename.bu : fn1, fn2[;|{]`
///
/// Returns `(file_stem, fns_str, has_metadata_block)`.
/// Errors when the `.bu` extension is missing (caller already guarantees it
/// is present, but this handles the inner extraction cleanly).
fn parse_entry_header(trimmed: &str, line_no: usize) -> Result<(String, String, bool), String> {
    let bu_pos = trimmed.find(".bu").ok_or_else(||
        format!("line {}: file entries must end with the .bu extension", line_no)
    )?;

    let file_stem = trimmed[..bu_pos].trim().to_string();
    if file_stem.is_empty() {
        return Err(format!("line {}: empty file name in entry", line_no));
    }

    // Everything after `.bu`, starting with `:`
    let after_bu = trimmed[bu_pos + 3..].trim_start();
    if !after_bu.starts_with(':') {
        return Err(format!("line {}: expected ':' after file name", line_no));
    }
    let rest = after_bu[1..].trim();

    let has_meta = rest.ends_with('{');
    let fns_str  = if has_meta {
        rest.trim_end_matches('{').trim()
    } else {
        rest.trim_end_matches(';').trim()
    };

    Ok((file_stem, fns_str.to_string(), has_meta))
}

/// Parse a metadata block `{ goal: "...", owner: "..." }`.
///
/// `start` points to the first line after the entry header's opening `{`.
/// `entry_indent` is the column of the entry line itself.
/// Returns `(goal, owner, next_i)` where `next_i` is the index after the
/// closing `}`.
fn parse_metadata_block(
    lines:        &[&str],
    start:        usize,
    entry_indent: usize,
    unit:         usize,
    entry_line:   usize,
) -> Result<(Option<String>, Option<String>, usize), String> {
    let mut goal  = None;
    let mut owner = None;
    let mut i     = start;
    let field_indent = entry_indent + unit;

    while i < lines.len() {
        let line    = lines[i];
        let trimmed = line.trim();

        if trimmed.is_empty() { i += 1; continue; }

        let indent = line.len() - line.trim_start().len();

        // Closing brace at the same indent as the entry line
        if trimmed == "}" && indent == entry_indent {
            return Ok((goal, owner, i + 1));
        }

        if indent == field_indent {
            if let Some(val) = parse_quoted_field(trimmed, "goal") {
                goal = Some(val);
            } else if let Some(val) = parse_quoted_field(trimmed, "owner") {
                owner = Some(val);
            }
            // Unknown metadata fields are silently ignored for forward compatibility
        }

        i += 1;
    }

    Err(format!(
        "line {}: metadata block opened here was never closed with '}}'",
        entry_line
    ))
}

/// Extract the value from a `key : "value"` or `key: "value"` field line.
/// Quotes are stripped. Returns `None` if the key doesn't match or the
/// value is empty.
fn parse_quoted_field(trimmed: &str, key: &str) -> Option<String> {
    if !trimmed.to_lowercase().starts_with(key) { return None; }
    let rest = trimmed[key.len()..].trim_start();
    if !rest.starts_with(':') { return None; }
    let val = rest[1..].trim().trim_matches('"');
    if val.is_empty() { None } else { Some(val.to_string()) }
}

/// Parse a folder header line into (Option<lang_ext>, folder_name).
///
/// Accepts these forms:
///   `python: my_folder`   → (Some("py"), "my_folder")
///   `rs: my_folder`       → (Some("rs"), "my_folder")
///   `my_folder`           → (None, "my_folder")
///
/// The folder name part has any trailing `:` or `{` stripped, and any
/// leading rank keyword (`war`, `theater`, etc.) removed so users do not need
/// to write ranks in blueprints — they are inferred from nesting depth.
fn parse_folder_header(trimmed: &str) -> (Option<String>, String) {
    let stripped = trimmed.trim_end_matches('{').trim().trim_end_matches(':').trim();

    const LANGS: &[(&str, &str)] = &[
        ("rust",   "rs"), ("rs",     "rs"),
        ("python", "py"), ("py",     "py"),
        ("c",      "c"),  ("cpp",    "cpp"),
        ("c++",    "cpp"),("go",     "go"),
        ("golang", "go"),
    ];

    const RANKS: &[&str] = &[
        "war", "theater", "battle", "strategy", "tactic", "skirmish",
    ];

    // "lang: [rank] folder_name" — e.g. "python: theater tools" or "python: tools"
    if let Some(colon) = stripped.find(':') {
        let prefix = stripped[..colon].trim().to_lowercase();
        let rest   = stripped[colon+1..].trim();
        if !rest.is_empty() {
            for (long, short) in LANGS {
                if prefix == *long {
                    return (Some(short.to_string()), strip_rank_prefix(rest, RANKS));
                }
            }
        }
    }

    // Plain folder line, possibly prefixed with a rank keyword
    (None, strip_rank_prefix(stripped, RANKS))
}

/// Strip a leading rank keyword + whitespace from `s`, e.g. "war my_project" → "my_project".
/// Returns `s` unchanged when no rank keyword is found.
fn strip_rank_prefix(s: &str, ranks: &[&str]) -> String {
    for rank in ranks {
        if let Some(rest) = s.strip_prefix(rank) {
            let rest = rest.trim_start();
            if !rest.is_empty() {
                return rest.to_string();
            }
        }
    }
    s.to_string()
}

// ── Blueprint → folder tree ───────────────────────────────────────────────────

pub struct BlueprintResult {
    pub root:          PathBuf,
    pub files_created: Vec<PathBuf>,
}

/// Scaffold a project from a parsed blueprint.
pub fn init_from_blueprint(
    parent:        &Path,
    name:          &str,
    nodes:         &[BlueprintNode],
    lang:          Option<&str>,
    blueprint_src: &str,
) -> Result<BlueprintResult, String> {
    let root = parent.join(name);
    if root.exists() {
        return Err(format!("'{}' already exists.", root.display()));
    }
    fs::create_dir_all(&root)
        .map_err(|e| format!("Could not create '{}': {}", root.display(), e))?;

    let mut files_created: Vec<PathBuf> = Vec::new();
    // (owner_name, relative_path_from_root) accumulated across the whole tree
    let mut owners: Vec<(String, String)> = Vec::new();

    let max_depth = tree_depth(nodes);
    let root_rank = rank_for_depth(max_depth as u8)
        .ok_or_else(|| "Blueprint tree is too deep (max 6 levels)".to_string())?;

    // Write root inventory.bu
    let mut root_inv = format!("#rank: {};\n", root_rank.name());
    if let Some(l) = lang {
        root_inv.push_str(&format!("\n#lang: {};\n", l));
    }
    let root_entries: Vec<&BlueprintNode> = nodes.iter()
        .filter(|n| matches!(n, BlueprintNode::Entry { .. }))
        .collect();
    if !root_entries.is_empty() {
        root_inv.push('\n');
        for e in root_entries {
            if let BlueprintNode::Entry { file, functions, .. } = e {
                root_inv.push_str(&format!("{}: {};\n", file, functions.join(", ")));
            }
        }
    }
    write_file(&root.join("inventory.bu"), &root_inv, &mut files_created)?;

    // Create stub .bu files for root-level entries
    for e in nodes.iter().filter(|n| matches!(n, BlueprintNode::Entry { .. })) {
        if let BlueprintNode::Entry { file, goal, owner, .. } = e {
            let stub = goal.as_deref()
                .map(|g| format!("// {}\n", g))
                .unwrap_or_default();
            write_file(&root.join(format!("{}.bu", file)), &stub, &mut files_created)?;
            if let Some(o) = owner {
                owners.push((o.clone(), format!("{}.bu", file)));
            }
        }
    }

    let child_folders: Vec<&BlueprintNode> = nodes.iter()
        .filter(|n| matches!(n, BlueprintNode::Folder { .. }))
        .collect();
    for node in child_folders {
        if let BlueprintNode::Folder { name: folder_name, lang: folder_lang, children } = node {
            let effective_lang = folder_lang.as_deref().or(lang);
            emit_blueprint_folder(
                &root, folder_name, children, max_depth - 1,
                effective_lang, &mut files_created, &mut owners, folder_name,
            )?;
        }
    }

    // Copy blueprint source and write README
    write_file(&root.join("blueprint.bu"), blueprint_src, &mut files_created)?;
    write_file(&root.join("README.md"), BULLANG_README, &mut files_created)?;

    // Generate work_division.md if any owners were declared
    if !owners.is_empty() {
        let md = generate_work_division_md(&owners);
        write_file(&root.join("work_division.md"), &md, &mut files_created)?;
    }

    Ok(BlueprintResult { root, files_created })
}

fn emit_blueprint_folder(
    parent:          &Path,
    name:            &str,
    children:        &[BlueprintNode],
    depth_remaining: usize,
    inherited_lang:  Option<&str>,
    created:         &mut Vec<PathBuf>,
    owners:          &mut Vec<(String, String)>,
    rel_path:        &str,
) -> Result<(), String> {
    let dir = parent.join(name);
    fs::create_dir_all(&dir)
        .map_err(|e| format!("Could not create '{}': {}", dir.display(), e))?;

    let rank = rank_for_depth(depth_remaining as u8)
        .ok_or_else(|| format!("Blueprint nesting too deep at '{}'", name))?;

    let mut inv = format!("#rank: {};\n", rank.name());
    if let Some(l) = inherited_lang {
        inv.push_str(&format!("#lang: {};\n", l));
    }

    let entries: Vec<&BlueprintNode> = children.iter()
        .filter(|n| matches!(n, BlueprintNode::Entry { .. }))
        .collect();
    if !entries.is_empty() {
        inv.push('\n');
        for e in entries {
            if let BlueprintNode::Entry { file, functions, .. } = e {
                inv.push_str(&format!("{}: {};\n", file, functions.join(", ")));
            }
        }
    }
    write_file(&dir.join("inventory.bu"), &inv, created)?;

    // Create a stub .bu file for every entry in this folder
    for e in children.iter().filter(|n| matches!(n, BlueprintNode::Entry { .. })) {
        if let BlueprintNode::Entry { file, goal, owner, .. } = e {
            let stub = goal.as_deref()
                .map(|g| format!("// {}\n", g))
                .unwrap_or_default();
            write_file(&dir.join(format!("{}.bu", file)), &stub, created)?;
            if let Some(o) = owner {
                owners.push((o.clone(), format!("{}/{}.bu", rel_path, file)));
            }
        }
    }

    for child in children {
        if let BlueprintNode::Folder { name: child_name, lang: child_lang, children: grandchildren } = child {
            let effective = child_lang.as_deref().or(inherited_lang);
            let child_rel = format!("{}/{}", rel_path, child_name);
            emit_blueprint_folder(
                &dir, child_name, grandchildren, depth_remaining - 1,
                effective, created, owners, &child_rel,
            )?;
        }
    }

    Ok(())
}

// ── Work division ─────────────────────────────────────────────────────────────

/// Generate the content of `work_division.md`, grouping files by owner.
fn generate_work_division_md(owners: &[(String, String)]) -> String {
    use std::collections::BTreeMap;

    let mut by_owner: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (owner, path) in owners {
        by_owner.entry(owner.as_str()).or_default().push(path.as_str());
    }

    let mut md = String::from("# Work Division\n\n");
    for (owner, files) in &by_owner {
        md.push_str(&format!("## {}\n\n", owner));
        for f in files {
            md.push_str(&format!("- {}\n", f));
        }
        md.push('\n');
    }
    md
}

fn tree_depth(nodes: &[BlueprintNode]) -> usize {
    let mut max = 0usize;
    for node in nodes {
        if let BlueprintNode::Folder { children, .. } = node {
            let child_depth = 1 + tree_depth(children);
            if child_depth > max { max = child_depth; }
        }
    }
    if max == 0 { 1 } else { max }
}

// ── Display ───────────────────────────────────────────────────────────────────

pub fn print_blueprint_tree(result: &BlueprintResult) {
    println!("created: {}", result.root.display());
    println!();
    let root = &result.root;
    for path in &result.files_created {
        let rel       = path.strip_prefix(root).unwrap_or(path);
        let depth     = rel.components().count().saturating_sub(1);
        let indent    = "  ".repeat(depth);
        let file_name = rel.file_name().and_then(|n| n.to_str()).unwrap_or("?");
        if file_name == "inventory.bu" && depth > 0 {
            let folder = rel.parent()
                .and_then(|p| p.file_name()).and_then(|n| n.to_str()).unwrap_or("?");
            println!("  {}{}/", "  ".repeat(depth - 1), folder);
        }
        let label = match file_name {
            "inventory.bu"     => format!("{} (inventory)", file_name),
            "blueprint.bu"     => format!("{} (blueprint — copied)", file_name),
            "work_division.md" => format!("{} (work division)", file_name),
            "README.md"        => file_name.to_string(),
            other if other.ends_with(".bu") => format!("{} (stub)", other),
            _                  => file_name.to_string(),
        };
        println!("  {}  {}", indent, label);
    }
}
