#ifndef BU_GENERIC_H
#define BU_GENERIC_H

/*
 * bu_generic.h — Bullang generic function support for C
 *
 * Bullang's user-defined generic functions (let f[T](...) -> ...) transpile to
 * C using a tagged union, BuVal. Every type parameter T becomes BuVal at the
 * C boundary. Arithmetic and comparison operations dispatch on the runtime tag.
 *
 * This file is auto-generated by bullang — do not edit.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include <math.h>

// ── Tag ───────────────────────────────────────────────────────────────────────

typedef enum {
    BU_I8, BU_I16, BU_I32, BU_I64,
    BU_U8, BU_U16, BU_U32, BU_U64,
    BU_F32, BU_F64,
    BU_BOOL, BU_CHAR, BU_STR, BU_PTR
} BuTag;

// ── Value ─────────────────────────────────────────────────────────────────────

typedef struct {
    BuTag tag;
    union {
        int8_t   i8;
        int16_t  i16;
        int32_t  i32;
        int64_t  i64;
        uint8_t  u8;
        uint16_t u16;
        uint32_t u32;
        uint64_t u64;
        float    f32;
        double   f64;
        bool     b;
        char     c;
        char    *str;
        void    *ptr;
    } val;
} BuVal;

// ── Constructors ──────────────────────────────────────────────────────────────

static inline BuVal bu_i8 (int8_t   v) { BuVal r; r.tag=BU_I8;   r.val.i8  =v; return r; }
static inline BuVal bu_i16(int16_t  v) { BuVal r; r.tag=BU_I16;  r.val.i16 =v; return r; }
static inline BuVal bu_i32(int32_t  v) { BuVal r; r.tag=BU_I32;  r.val.i32 =v; return r; }
static inline BuVal bu_i64(int64_t  v) { BuVal r; r.tag=BU_I64;  r.val.i64 =v; return r; }
static inline BuVal bu_u8 (uint8_t  v) { BuVal r; r.tag=BU_U8;   r.val.u8  =v; return r; }
static inline BuVal bu_u16(uint16_t v) { BuVal r; r.tag=BU_U16;  r.val.u16 =v; return r; }
static inline BuVal bu_u32(uint32_t v) { BuVal r; r.tag=BU_U32;  r.val.u32 =v; return r; }
static inline BuVal bu_u64(uint64_t v) { BuVal r; r.tag=BU_U64;  r.val.u64 =v; return r; }
static inline BuVal bu_f32(float    v) { BuVal r; r.tag=BU_F32;  r.val.f32 =v; return r; }
static inline BuVal bu_f64(double   v) { BuVal r; r.tag=BU_F64;  r.val.f64 =v; return r; }
static inline BuVal bu_bool(bool    v) { BuVal r; r.tag=BU_BOOL; r.val.b   =v; return r; }
static inline BuVal bu_char(char    v) { BuVal r; r.tag=BU_CHAR; r.val.c   =v; return r; }
static inline BuVal bu_str (char   *v) { BuVal r; r.tag=BU_STR;  r.val.str =v; return r; }
static inline BuVal bu_ptr (void   *v) { BuVal r; r.tag=BU_PTR;  r.val.ptr =v; return r; }

// ── Numeric coercion ──────────────────────────────────────────────────────────

static inline double bu_val_as_f64(BuVal v) {
    switch (v.tag) {
        case BU_I8:  return (double)v.val.i8;
        case BU_I16: return (double)v.val.i16;
        case BU_I32: return (double)v.val.i32;
        case BU_I64: return (double)v.val.i64;
        case BU_U8:  return (double)v.val.u8;
        case BU_U16: return (double)v.val.u16;
        case BU_U32: return (double)v.val.u32;
        case BU_U64: return (double)v.val.u64;
        case BU_F32: return (double)v.val.f32;
        case BU_F64: return v.val.f64;
        case BU_BOOL: return v.val.b ? 1.0 : 0.0;
        default:     return 0.0;
    }
}

/* Return a new BuVal of the same tag as `a`, with the given double value. */
static inline BuVal bu_val_from_f64(BuTag tag, double d) {
    switch (tag) {
        case BU_I8:  return bu_i8 ((int8_t)d);
        case BU_I16: return bu_i16((int16_t)d);
        case BU_I32: return bu_i32((int32_t)d);
        case BU_I64: return bu_i64((int64_t)d);
        case BU_U8:  return bu_u8 ((uint8_t)d);
        case BU_U16: return bu_u16((uint16_t)d);
        case BU_U32: return bu_u32((uint32_t)d);
        case BU_U64: return bu_u64((uint64_t)d);
        case BU_F32: return bu_f32((float)d);
        case BU_F64: return bu_f64(d);
        default:     return bu_i64((int64_t)d);
    }
}

// ── Boolean extraction ────────────────────────────────────────────────────────

static inline bool bu_val_truthy(BuVal v) {
    switch (v.tag) {
        case BU_BOOL: return v.val.b;
        case BU_I8:  return v.val.i8  != 0;
        case BU_I16: return v.val.i16 != 0;
        case BU_I32: return v.val.i32 != 0;
        case BU_I64: return v.val.i64 != 0;
        case BU_U8:  return v.val.u8  != 0;
        case BU_U16: return v.val.u16 != 0;
        case BU_U32: return v.val.u32 != 0;
        case BU_U64: return v.val.u64 != 0;
        case BU_F64: return v.val.f64 != 0.0;
        case BU_STR: return v.val.str != NULL && v.val.str[0] != '\0';
        case BU_PTR: return v.val.ptr != NULL;
        default:     return false;
    }
}

// ── Arithmetic ────────────────────────────────────────────────────────────────

static inline BuVal bu_val_add(BuVal a, BuVal b) {
    if (a.tag == BU_STR && b.tag == BU_STR) {
        /* String concatenation: allocate a new buffer */
        size_t la = strlen(a.val.str), lb = strlen(b.val.str);
        char  *s  = (char *)malloc(la + lb + 1);
        memcpy(s, a.val.str, la);
        memcpy(s + la, b.val.str, lb);
        s[la + lb] = '\0';
        return bu_str(s);
    }
    return bu_val_from_f64(a.tag, bu_val_as_f64(a) + bu_val_as_f64(b));
}
static inline BuVal bu_val_sub(BuVal a, BuVal b) {
    return bu_val_from_f64(a.tag, bu_val_as_f64(a) - bu_val_as_f64(b));
}
static inline BuVal bu_val_mul(BuVal a, BuVal b) {
    return bu_val_from_f64(a.tag, bu_val_as_f64(a) * bu_val_as_f64(b));
}
static inline BuVal bu_val_div(BuVal a, BuVal b) {
    double d = bu_val_as_f64(b);
    if (d == 0.0) return bu_i64(0);
    return bu_val_from_f64(a.tag, bu_val_as_f64(a) / d);
}
static inline BuVal bu_val_mod(BuVal a, BuVal b) {
    int64_t ia = (int64_t)bu_val_as_f64(a);
    int64_t ib = (int64_t)bu_val_as_f64(b);
    return bu_i64(ib != 0 ? ia % ib : 0);
}
static inline BuVal bu_val_neg(BuVal a) {
    return bu_val_from_f64(a.tag, -bu_val_as_f64(a));
}

// ── Comparison (return BuVal{BOOL}) ──────────────────────────────────────────

static inline BuVal bu_val_eq(BuVal a, BuVal b) {
    if (a.tag == BU_STR && b.tag == BU_STR)
        return bu_bool(strcmp(a.val.str, b.val.str) == 0);
    if (a.tag == BU_BOOL && b.tag == BU_BOOL)
        return bu_bool(a.val.b == b.val.b);
    if (a.tag == BU_CHAR && b.tag == BU_CHAR)
        return bu_bool(a.val.c == b.val.c);
    return bu_bool(bu_val_as_f64(a) == bu_val_as_f64(b));
}
static inline BuVal bu_val_ne(BuVal a, BuVal b) {
    BuVal r = bu_val_eq(a, b); r.val.b = !r.val.b; return r;
}
static inline BuVal bu_val_lt(BuVal a, BuVal b) {
    return bu_bool(bu_val_as_f64(a) < bu_val_as_f64(b));
}
static inline BuVal bu_val_gt(BuVal a, BuVal b) {
    return bu_bool(bu_val_as_f64(a) > bu_val_as_f64(b));
}
static inline BuVal bu_val_le(BuVal a, BuVal b) {
    return bu_bool(bu_val_as_f64(a) <= bu_val_as_f64(b));
}
static inline BuVal bu_val_ge(BuVal a, BuVal b) {
    return bu_bool(bu_val_as_f64(a) >= bu_val_as_f64(b));
}

// ── Boolean operators ─────────────────────────────────────────────────────────

static inline BuVal bu_val_and(BuVal a, BuVal b) {
    return bu_bool(bu_val_truthy(a) && bu_val_truthy(b));
}
static inline BuVal bu_val_or(BuVal a, BuVal b) {
    return bu_bool(bu_val_truthy(a) || bu_val_truthy(b));
}
static inline BuVal bu_val_not(BuVal a) {
    return bu_bool(!bu_val_truthy(a));
}

#endif /* BU_GENERIC_H */
