//! README generation: written on `bullarchy init`, deleted on `bullarchy convert`.

use std::path::Path;

pub fn write_project_readme(project_root: &Path) {
    let path = project_root.join("README.md");
    match std::fs::write(&path, bullang_readme()) {
        Ok(_)  => println!("  wrote README.md (delete after reading — removed automatically on convert)"),
        Err(e) => eprintln!("warning: could not write README.md: {}", e),
    }
}

pub fn delete_project_readme(project_root: &Path) {
    let path = project_root.join("README.md");
    if path.exists() {
        if let Err(e) = std::fs::remove_file(&path) {
            eprintln!("warning: could not remove README.md: {}", e);
        }
    }
}

pub fn bullang_readme() -> &'static str {
r#"# Bullang project — Quick-start README

> Generated by `bullarchy init`. Deleted automatically when you run `bullarchy convert`.

---

## Project structure

Each folder has a **rank**. Functions defined at a lower rank are available one rank above — never sideways, never upward from there.

```
war
└── theater
    └── battle
        └── strategy
            └── tactic
                └── skirmish
```

| Rank | Depth |
|---|---|
| skirmish | 1 |
| tactic   | 2 |
| strategy | 3 |
| battle   | 4 |
| theater  | 5 |
| war      | 6 |

---

## inventory.bu

Every folder has one. Order: directives → structs/enums → file manifest.

```
#rank: tactic;
#lang: rs;
#lib:  stdio.h;

struct Point {
    x : i32,
    y : i32,
}

enum Direction {
    North,
    South,
    East,
    West,
}

math   : add, subtract;
shapes : area, perimeter;
```

| Directive | Required | Description |
|---|---|---|
| `#rank:` | yes | Folder rank |
| `#lang:` | no  | Target backend: rs py c cpp go |
| `#lib:`  | no  | C/C++ header — repeatable |

---

## Functions

```
let add(a: i32, b: i32) -> result: i32 {
    (a, b) : a + b -> {result};
}
```

No return value:
```
let greet(name: String) {
    ("Hello {name}\n") : builtin::out -> {};
}
```

- All functions are always public.
- Up to **5 pipes** per function, or **one escape block** — not both.
- The last pipe's binding is the return value.

---

## Pipes

```
(inputs) : expression -> {binding};
```

| Part | Description |
|---|---|
| `(inputs)` | Idents or literals passed to the expression |
| `: expression` | Arithmetic, function call, or builtin |
| `-> {binding}` | Name the result. Use `{}` to discard. |

Examples:
```
(a, b)          : a + b            -> {sum};
(sum)           : builtin::to_string -> {s};
("Result: {s}") : builtin::out     -> {};
(Direction.North) : some_fn        -> {result};
```

---

## Types

| Type | Description |
|---|---|
| `i32` / `i64` | Integer |
| `f64`         | Float |
| `bool`        | true / false |
| `String`      | UTF-8 string |
| `(A, B)`      | Tuple |
| `[T; N]`      | Fixed-size array |
| `Unit`        | No return value |

Struct and enum types are defined in `inventory.bu` and available in the same folder and one rank above.

---

## Expressions

```
a + b   a - b   a * b   a / b   a % b
a == b  a != b  a < b   a <= b  a > b  a >= b
a && b  a || b  !a      -a
"hello {name}"          string interpolation
s[i]   s[i..j]          index / slice
```

---

## Builtins

```
(s)      : builtin::to_upper  -> {upper};
(a, b)   : builtin::min       -> {smaller};
```

| Category | Builtins |
|---|---|
| Math      | `abs` `pow` `powf` `sqrt` `log` `exp` `min` `max` `clamp` |
| Cond      | `tern` |
| String    | `to_upper` `to_lower` `trim` `len` `starts_with` `ends_with` `replace_str` `to_string` `parse_i64` |
| Algo      | `swap` `insertion_sort` `quick_sort` `merge_sort` `radix_sort` |
| I/O       | `in` `out` `open` `close` `time` |
| System    | `args` `exit` `env` `sleep` |

File descriptors: `0` stdin · `1` stdout · `2` stderr · `3+` opened files.

Run `bullang stdlib` for full signatures.

---

## Escape blocks

One block per function. Cannot mix with pipes.

```
let fast(a: i32, b: i32) -> result: i32 {
    @rust
        let result = a + b;
    @end
}
```

Supported: `@rust` `@python` `@c` `@cpp` `@go`

The block's backend must match the folder's `#lang:`.

---

## Bullarchy commands

```
command -> init my_project
command -> init my_project --depth 3 --lang c --lib stdio.h
command -> init my_project --blueprint blueprint.bu

command -> convert my_project        # auto-detect lang from #lang:
command -> convert my_project py     # language override
command -> convert path/to/file.bu
command -> convert path/to/file.bu rs
command -> convert path/to/file.bu out.rs

command -> fmt
command -> fmt --dry-run
command -> check
command -> editor-setup
command -> update
```

---

## Typical workflow

```sh
# 1. Scaffold
bullarchy
command -> init my_project --depth 3 --lang rs

# 2. Write functions in .bu source files

# 3. Validate
command -> check

# 4. Format if needed
command -> fmt

# 5. Convert — this README is deleted automatically
command -> convert my_project

# 6. Compile
cd _my_project && cargo build
```

---

*See the full book: https://github.com/My-sidequests/Bullang*
"#
}
